env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}
jobs:
  cherry-picker-on-closed:
    if: github.event.action == 'closed' && github.event.sender.login == 'copybara-service[bot]'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      if: github.event.pull_request
      name: Run cherrypicker on closed PR
      uses: bazelbuild/continuous-integration/actions/cherry_picker@fcd3cdd216acf5b78449ae6c05da1c789f5ef76c
      with:
        is-prod: true
        pr-number: ${{ github.event.number }}
        triggered-on: closed
    - continue-on-error: true
      if: github.event.issue
      name: Run cherrypicker on closed issue
      uses: bazelbuild/continuous-integration/actions/cherry_picker@fcd3cdd216acf5b78449ae6c05da1c789f5ef76c
      with:
        is-prod: true
        pr-number: ${{ github.event.issue.number }}
        triggered-on: closed
  cherry-picker-on-milestoned:
    if: github.event.action == 'milestoned'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      if: startsWith(github.event.issue.body, 'Forked from')
      name: Run cherrypicker on comment
      uses: bazelbuild/continuous-integration/actions/cherry_picker@fcd3cdd216acf5b78449ae6c05da1c789f5ef76c
      with:
        is-prod: true
        milestone-title: ${{ github.event.milestone.title }}
        milestoned-issue-number: ${{ github.event.issue.number }}
        pr-number: ${{ github.event.issue.body }}
        triggered-on: commented
    - continue-on-error: true
      if: startsWith(github.event.issue.body, '### Commit IDs')
      name: Run cherrypicker on demand
      uses: bazelbuild/continuous-integration/actions/cherry_picker@fcd3cdd216acf5b78449ae6c05da1c789f5ef76c
      with:
        is-prod: true
        issue-body: ${{ github.event.issue.body }}
        issue-title: ${{ github.event.issue.title }}
        milestone-title: ${{ github.event.milestone.title }}
        milestoned-issue-number: ${{ github.event.issue.number }}
        triggered-on: ondemand
name: cherry-picker
on:
  repository_dispatch:
    types: trigger-ga___cherry-picker.yml
permissions:
  contents: read
