jobs:
  label-issues-policy:
    permissions:
      contents: read
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      id: issue-parser
      name: Parse issue form
      uses: stefanbuck/github-issue-parser@c1a559d78bfb8dd05216dab9ffd2b91082ff5324
      with:
        template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}
    - continue-on-error: true
      name: Set labels based on policy
      uses: redhat-plumbers-in-action/advanced-issue-labeler@d498805e5c7c0658e336948b3363480bcfd68da6
      with:
        issue-form: ${{ steps.issue-parser.outputs.jsonString }}
        template: ${{ matrix.template }}
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        template:
        - bug_report.yml
        - feature_request.yml
name: Issue labeler
on:
  repository_dispatch:
    types: trigger-ga___issue-labeler.yml
