jobs:
  triage:
    if: ${{ github.event.pull_request.draft == false && github.event.pull_request.user.login
      != 'bazel-io' }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
name: PR Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
permissions:
  contents: read
