jobs:
  release-helper:
    if: startsWith(github.event.comment.body, '@bazel-io ')
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      name: Run helper
      uses: bazelbuild/continuous-integration/actions/release-helper@fcd3cdd216acf5b78449ae6c05da1c789f5ef76c
      with:
        token: ${{ secrets.BAZEL_IO_TOKEN }}
name: release-helper
on:
  repository_dispatch:
    types: trigger-ga___release-helper.yml
permissions:
  contents: read
