jobs:
  remove-label:
    permissions:
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
      with:
        labels: 'awaiting-PR-merge

          awaiting-review'
name: Remove PR Labels
on:
  repository_dispatch:
    types: trigger-ga___remove-labels.yml
permissions:
  contents: read
