jobs:
  stale:
    name: Track and close stale issues/PRs
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit
    - continue-on-error: true
      name: Track and close stale issues/PRs
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e
      with:
        ascending: true
        close-issue-message: 'This issue has been automatically closed due to inactivity.
          If you''re still interested in pursuing this, please post `@bazelbuild/triage`
          in a comment here and we''ll take a look. Thanks!

          '
        close-issue-reason: not_planned
        close-pr-message: 'This pull request has been automatically closed due to
          inactivity. If you''re still interested in pursuing this, please post `@bazelbuild/triage`
          in a comment here and we''ll take a look. Thanks!

          '
        days-before-issue-close: 90
        days-before-issue-stale: 430
        days-before-pr-close: 90
        days-before-pr-stale: 430
        exempt-draft-pr: true
        exempt-issue-labels: not stale,awaiting-bazeler,untriaged,P0,P1,P2,good first
          issue,help wanted
        exempt-pr-labels: not stale,awaiting-review,awaiting-PR-merge,P0,P1,P2
        operations-per-run: 500
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-label: stale
        stale-issue-message: 'Thank you for contributing to the Bazel repository!
          This issue has been marked as stale since it has not had any activity in
          the last 1+ years. It will be closed in the next 90 days unless any other
          activity occurs. If you think this issue is still relevant and should stay
          open, please post any comment here and the issue will no longer be marked
          as stale.

          '
        stale-pr-label: stale
        stale-pr-message: 'Thank you for contributing to the Bazel repository! This
          pull request has been marked as stale since it has not had any activity
          in the last 1+ years. It will be closed in the next 90 days unless any other
          activity occurs. If you think this PR is still relevant and should stay
          open, please post any comment here and the PR will no longer be marked as
          stale.

          '
name: Mark stale issues and pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  contents: read
